import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./splash.png'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],
	"back": Icons['chevron-left-dark'],
	"accept": Icons['accept'],
	"discard": Icons['discard'],

	"USA": require('./USA.png'),
	"CSA": require('./CSA.png'),

	"Accepted": require('./Accepted.png'),
	"InTransit": require('./InTransit.png'),
	"Delay1": require('./Delay1.png'),
	"Delay2": require('./Delay2.png'),
	"Distorted": require('./Distorted.png'),
	"Stopped": require('./Stopped.png'),	

	"orderadd": require('./orderadd.png'),
	"orderremove": require('./orderremove.png'),
	"orderinitiative": require('./orderinitiative.png'),
	"orderaccept": require('./orderaccept.png'),
	"orderreduce": require('./orderreduce.png'),
	"orderstop": require('./orderstop.png'),

	"csa-brigade-destroyed": require('./csa-brigade-destroyed.png'),
	"csa-brigade-wrecked": require('./csa-brigade-wrecked.png'),
	"csa-brigade": require('./csa-brigade.png'),
	"csa-division-wrecked": require('./csa-division-wrecked.png'),
	"csa-division": require('./csa-division.png'),
	"csa-corps": require('./csa-corps.png'),

	"usa-brigade-destroyed": require('./usa-brigade-destroyed.png'),
	"usa-brigade-wrecked": require('./usa-brigade-wrecked.png'),
	"usa-brigade": require('./usa-brigade.png'),
	"usa-division-wrecked": require('./usa-division-wrecked.png'),
	"usa-division": require('./usa-division.png'),
	"usa-corps": require('./usa-corps.png'),

	"checked": require('./checked_checkbox.png'),
	"unchecked": require('./unchecked_checkbox.png'),
	"checkmark": require('./checkmark.png'),
	"casualty": require('./casualty.png'),
	"straggler": require('./straggler.png'),
	"skull": require('./skull.png'),

	"casualty-1": require('./casualty1.png'),
	"casualty-2": require('./casualty2.png'),
	"casualty-3": require('./casualty3.png'),
	"casualty-4": require('./casualty4.png'),
	"casualty-5": require('./casualty5.png'),
	"straggler-1": require('./straggler1.png'),
	"straggler-2": require('./straggler2.png'),
	"straggler-3": require('./straggler3.png'),
	"straggler-4": require('./straggler4.png'),
	"straggler-5": require('./straggler5.png'),
	"N": require('./state-normal.png'),
	"NE": require('./state-normal.png'),
	"BL": require('./state-bloodlust.png'),
	"SH": require('./state-shaken.png'),
	"DG": require('./state-disorganized.png'),
	"R": require('./state-routed.png'),
	"retreat-1": require('./retreat1.png'),
	"retreat-2": require('./retreat2.png'),

	"lowammo": require('./lowammo.png'),
	"leaderloss": require('./leaderloss.png'),

	"cc-Attacker": require('../res/cc-attacker.png'),
	"cc-Defender": require('../res/cc-defender.png'),

	"intheirquietfields": require('./intheirquietfields.jpg'),	
	"thunderatthecrossroads": require('./thunderatthecrossroads.jpg'),
	"augustfury": require('./augustfury.jpg'),
	"barrenvictory": require('./barrenvictory.jpg'),
	"bloodyroadssouth": require('./bloodyroadssouth.jpg'),
	"perryville": require('./perryville.jpg'),
	"embraceanangrywind": require('./embraceanangrywind.jpg'),
	"nobetterplacetodie": require('./nobetterplacetodie.jpg'),	
	"aprilsharvest": require('./aprilsharvest.jpg'),
	"championhill": require('./championhill.jpg'),		
	"gainesmill": require('./gainesmill.jpg'),
	"sevenpines": require('./sevenpines.jpg'),
	"malvernhill": require('./malvernhill.jpg'),
	"sevendays": require('./sevendays.jpg'),
	"threebattlesofmanassas": require('./threebattlesofmanassas.jpg'),
	"strikethemablow": require('./strikethemablow.jpg')
};
