module.exports = {
    RESET: 'RESET',
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN',
    PREV_PHASE: 'PREV_PHASE',
    NEXT_PHASE: 'NEXT_PHASE',
    NEXT_PLAYER: 'NEXT_PLAYER',
    SET_PLAYER: 'SET_PLAYER',

    SET_COUNTRY: 'SET_COUNTRY',    
    SET_ORDERS: 'SET_ORDERS',
    ADD_ORDER: 'ADD_ORDER',
    UPDATE_ORDER: 'UPDATE_ORDER',
    REMOVE_ORDER: 'REMOVE_ORDER',    
    SET_ARTYAMMO: 'SET_ARTYAMMO',
    SET_VP: 'SET_VP',
    SET_ROSTER: 'SET_ROSTER',    
    UPDATE_BRIGADE: 'UPDATE_BRIGADE',    

    SELECT_ORDER: 'SELECT_ORDER',
    UPDATE_SELECTED_ORDER: 'UPDATE_SELECTED_ORDER',
    RESET_ORDER: 'RESET_ORDER'
};
