module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN',
    PREV_PHASE: 'PREV_PHASE',
    NEXT_PHASE: 'NEXT_PHASE',
    NEXT_PLAYER: 'NEXT_PLAYER',
    SET_PLAYER: 'SET_PLAYER',

    SET_CSA_ARTYAMMO: 'SET_CSA_ARTYAMMO',
    SET_CSA_VP: 'SET_CSA_VP',
    SET_USA_ARTYAMMO: 'SET_USA_ARTYAMMO',
    SET_USA_VP: 'SET_USA_VP',

    SELECT_ORDER: 'SET_ORDER',
    ADD_ORDER: 'ADD_ORDER',
    UPDATE_ORDER: 'UPDATE_ORDER',
    REMOVE_ORDER: 'REMOVE_ORDER'    
};
