module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN',
    PREV_PHASE: 'PREV_PHASE',
    NEXT_PHASE: 'NEXT_PHASE',
    NEXT_PLAYER: 'NEXT_PLAYER',
    SET_PLAYER: 'SET_PLAYER',

    SET_CSA_ARTYAMMO: 'SET_CSA_ARTYAMMO',
    SET_CSA_VP: 'SET_CSA_VP',
    SET_CSA_ORDER: 'SET_CSA_ORDER',
    ADD_CSA_ORDER: 'ADD_CSA_ORDER',
    UPDATE_CSA_ORDER: 'UPDATE_CSA_ORDER',
    REMOVE_CSA_ORDER: 'REMOVE_CSA_ORDER',

    SET_USA_ARTYAMMO: 'SET_USA_ARTYAMMO',
    SET_USA_VP: 'SET_USA_VP',
    SET_USA_ORDER: 'SET_USA_ORDER',
    ADD_USA_ORDER: 'ADD_USA_ORDER',
    UPDATE_USA_ORDER: 'UPDATE_USA_ORDER',
    REMOVE_USA_ORDER: 'REMOVE_USA_ORDER'    
};
