module.exports = {
	"logo": require('../res/logo.png'),
	"splash": require('../res/splash.png'),
	"menu": require('../res/hamburger-dark.png'),
	"info": require('../res/info-dark.png'),

	"arrow-down": require('../res/arrow-down.png'),
	"arrow-right": require('../res/arrow-right.png'),

	"refreshButton": require('../res/refresh-dark.png'),
	"prevButton":	require('../res/ic_action_previous_item.png'),
	"nextButton": require('../res/ic_action_next_item.png'),
	"checked": require('../res/checked_checkbox.png'),
	"unchecked": require('../res/unchecked_checkbox.png'),
	"checkmark": require('../res/checkmark.png'),
	"calendar": require('../res/calendar.png'),
	"clock": require('../res/clock.png'),

	"select": require('../res/select.png'),
	"add": require('../res/add.png'),
	"remove": require('../res/remove.png'),
	"accept": require('../res/accept.png'),
	"discard": require('../res/reject.png'),

	"casualty-1": require('../res/casualty1.png'),
	"casualty-2": require('../res/casualty2.png'),
	"casualty-3": require('../res/casualty3.png'),
	"casualty-4": require('../res/casualty4.png'),
	"casualty-5": require('../res/casualty5.png'),
	"straggler-1": require('../res/straggler1.png'),
	"straggler-2": require('../res/straggler2.png'),
	"straggler-3": require('../res/straggler3.png'),
	"straggler-4": require('../res/straggler4.png'),
	"straggler-5": require('../res/straggler5.png'),
	"BL": require('../res/state-bloodlust.png'),
	"SH": require('../res/state-shaken.png'),
	"DG": require('../res/state-disorganized.png'),
	"R": require('../res/state-routed.png'),
	"retreat-1": require('../res/retreat1.png'),
	"retreat-2": require('../res/retreat2.png'),

	"lowammo": require('../res/lowammo.png'),
	"leaderloss": require('../res/leaderloss.png'),

	"casualty": require('../res/casualty.png'),
	"straggler": require('../res/straggler.png'),
	"skull": require('../res/skull.png'),

	"CSA": require('../res/CSA.png'),
	"USA": require('../res/USA.png'),

	"csa-brigade-destroyed": require('../res/csa-brigade-destroyed.png'),
	"csa-brigade-wrecked": require('../res/csa-brigade-wrecked.png'),
	"csa-brigade": require('../res/csa-brigade.png'),
	"csa-division-wrecked": require('../res/csa-division-wrecked.png'),
	"csa-division": require('../res/csa-division.png'),
	"csa-corps": require('../res/csa-corps.png'),

	"usa-brigade-destroyed": require('../res/usa-brigade-destroyed.png'),
	"usa-brigade-wrecked": require('../res/usa-brigade-wrecked.png'),
	"usa-brigade": require('../res/usa-brigade.png'),
	"usa-division-wrecked": require('../res/usa-division-wrecked.png'),
	"usa-division": require('../res/usa-division.png'),
	"usa-corps": require('../res/usa-corps.png'),

	"Accepted": require('../res/Accepted.png'),
	"InTransit": require('../res/InTransit.png'),
	"Delay1": require('../res/Delay1.png'),
	"Delay2": require('../res/Delay2.png'),
	"Distorted": require('../res/Distorted.png'),
	"Stopped": require('../res/Stopped.png'),

	"aprilsharvest": require('../res/aprilsharvest.jpg'),
	"augustfury": require('../res/augustfury.jpg'),
	"championhill": require('../res/championhill.jpg'),
	"intheirquietfields": require('../res/intheirquietfields.jpg'),
	"nobetterplacetodie": require('../res/nobetterplacetodie.jpg'),
	"sevendays": require('../res/sevendays.jpg'),
	"sevenpines": require('../res/sevenpines.jpg'),
	"strikethemablow": require('../res/strikethemablow.jpg'),
	"threebattlesofmanassas": require('../res/threebattlesofmanassas.jpg'),
	"thunderatthecrossroads": require('../res/thunderatthecrossroads.jpg')
};
